name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'maintenance', 'deps']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: 'Minor internal improvements.'
template: |
  ## What’s Changed
  $CHANGES

  ## Container Images
  - `ghcr.io/${{ repo_owner }}/${{ repo_name }}:latest`
  - `ghcr.io/${{ repo_owner }}/${{ repo_name }}:$NEXT_PATCH_VERSION`
